# Generated by Django 5.2.7 on 2026-01-10 04:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_deleted_by_receiver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_deleted_for_everyone',
            new_name='is_deleted_globally',
        ),
        migrations.RemoveField(
            model_name='message',
            name='deleted_by_receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='deleted_by_sender',
        ),
        migrations.AddField(
            model_name='message',
            name='hidden_by',
            field=models.ManyToManyField(blank=True, related_name='hidden_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
