# Generated by Django 5.2.7 on 2026-01-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_profile_picture_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
